name: Playwright Tests

on:
  # Exécution manuelle depuis l'interface GitHub
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Fichier de test à exécuter'
        required: true
        type: choice
        options:
          - 'tests/static.spec.ts'
          - 'tests/github.spec.ts'
          - 'tests/mdn.spec.ts'
          - 'all'
        default: 'all'
      browser:
        description: 'Navigateur à utiliser'
        required: true
        type: choice
        options:
          - 'chromium'
          - 'firefox'
          - 'webkit'
          - 'all'
        default: 'chromium'
      headed:
        description: 'Exécuter en mode visuel'
        required: true
        type: boolean
        default: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm ci
        if [ "${{ github.event.inputs.headed }}" = "true" ]; then
          sudo apt-get update
          sudo apt-get install -y xvfb
        fi

    - name: Install Playwright Browsers
      run: |
        if [ "${{ github.event.inputs.browser }}" = "all" ]; then
          npx playwright install --with-deps
        else
          npx playwright install --with-deps ${{ github.event.inputs.browser }}
        fi

    - name: Create references directory
      run: mkdir -p references

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.headed }}" = "true" ]; then
          # Utiliser xvfb-run pour le mode visuel
          if [ "${{ github.event.inputs.test_file }}" = "all" ]; then
            if [ "${{ github.event.inputs.browser }}" = "all" ]; then
              xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npx playwright test --headed
            else
              xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npx playwright test --headed --project=${{ github.event.inputs.browser }}
            fi
          else
            if [ "${{ github.event.inputs.browser }}" = "all" ]; then
              xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npx playwright test ${{ github.event.inputs.test_file }} --headed
            else
              xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npx playwright test ${{ github.event.inputs.test_file }} --headed --project=${{ github.event.inputs.browser }}
            fi
          fi
        else
          # Mode headless normal
          if [ "${{ github.event.inputs.test_file }}" = "all" ]; then
            if [ "${{ github.event.inputs.browser }}" = "all" ]; then
              npx playwright test
            else
              npx playwright test --project=${{ github.event.inputs.browser }}
            fi
          else
            if [ "${{ github.event.inputs.browser }}" = "all" ]; then
              npx playwright test ${{ github.event.inputs.test_file }}
            else
              npx playwright test ${{ github.event.inputs.test_file }} --project=${{ github.event.inputs.browser }}
            fi
          fi
        fi

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: |
          playwright-report/
          test-results/
          references/
        retention-days: 30
